# Elena Yatzeck Homework Week 05

Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.): 

1. __What does Pandas stand for?__ Python Data Analysis or Panel Data
2. __What are the 2 collections used in Pandas?__ DataFrames and Series
3. __Name 4 things Pandas can do for us.__ It has functions for analyzing, cleaning, exploring, and manipulating data
4. __To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?__  Question:  do you mean df.sort_values()?  Is there a df.sort()?  If df.sort_values(), keyword is inplace=True
5. __What is a CSV?__  A CSV is a comma-separated values file, which allows data to be saved in a tabular format.
6. __When cleaning data what values do we not like in our data?__ nulls, values of the wrong datatype (example:  a character string in a column which should have all ints)

#### **Please Complete this Coding Exercise:**

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

In [3]:
import numpy as np

numbers = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11,12]])
print(numbers.shape)
reshapeArray = numbers.reshape(2,3,2)
print(reshapeArray)


(2, 6)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

In [4]:
linspaceArray = np.linspace(start = 0, stop = 20, num = 6)
print(linspaceArray)

[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [5]:
from copy import copy, deepcopy
dpArray = deepcopy(linspaceArray)
print(dpArray)

[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```

In [6]:
newArray = np.append(([[25, 16]]), np.append(([[11, 2], [13, 4]]),([[7, 81], [5, 6], [11, 12]])))
print(newArray)

[25 16 11  2 13  4  7 81  5  6 11 12]


11. Sort 'newArray' in order into 'sortedArray'

In [7]:
sortedArray = np.sort(newArray)
print(sortedArray)

[ 2  4  5  6  7 11 11 12 13 16 25 81]



12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.



In [8]:
# The solution described in class was to reshape the array from (2,3,2) to something divisible by 4, then unpack.
reshape_array_again = reshapeArray.reshape(4,3)
print(reshape_array_again)

### Unpack the array
a, b, c, d = reshape_array_again
print("a = ", a)
print("b = ", b)
print("c = ",c)
print("d = ", d)
print("The data type of d ...", type(c))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a =  [1 2 3]
b =  [4 5 6]
c =  [7 8 9]
d =  [10 11 12]
The data type of d ... <class 'numpy.ndarray'>


13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    ```


In [9]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.sort(np.append(one, np.append(two,three)))

print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [10]:
# sec 1
print(comboArray[1])

# sec 2
print(comboArray[2:])

# sec 3
print(comboArray[3:13])

# sec 4
print(comboArray[-6:])

# sec 5
print(comboArray[-28:-10])

# sec 6
print(comboArray[20::2])

# sec 7 -- we agreed in class to do this as "from the last element moving backward, every 5th element"
print(comboArray[::-5])


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[24 26]
[27 22 15 10  3]


15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object



In [11]:
import pandas as pd

i = pd.Series(["Flour","Milk","Eggs","Spam"],name="Ingredients")
q = pd.Series([4, 1, 2, 1],name="Quantity")
u = pd.Series(["cups","cup","large","can"],name="Unit")

Dinner = pd.concat([i, q, u], axis=1) 
print(Dinner)
print(type(Dinner))


  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can
<class 'pandas.core.frame.DataFrame'>


16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```


In [12]:
studentDict = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData = pd.DataFrame(studentDict)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


17. Add a new column to the DataFrame with the following deserts:

In [13]:
studentData["desserts"] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [14]:
18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

SyntaxError: invalid syntax (2976563912.py, line 1)

In [ ]:
studentData.sort_values(["Name","address"],ascending=[True,True])

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```



In [ ]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [ ]:
veggieDict = {'Name': ['Carrot', 'Eggplant', 'Avocado'],
            'Color': ['Orange', 'Purple','Green'],
            'Better': ['Raw', 'Cooked', 'Mashed']
        }
veggieData = pd.DataFrame(veggieDict)
veggieDict.to_csv('veggies.csv')

newVeggieData = pd.read_csv('veggies.csv')
newVeggieData['Feed']=['Rabbit','Deer','Squirrel']
newVeggieData.to_csv('newVeggies.csv')